#!/usr/bin/env bash

exec >> /var/log/start_mysql.sh.log 2>&1
set -x

# Stop on error
set -e

DATA_DIR=/data

# test if DATA_DIR has content
if [[ ! "$(ls -A $DATA_DIR)" ]]; then
  source /usr/bin/first_run.sh
else
  source /usr/bin/normal_run.sh
fi

wait_for_mysql_and_run_post_start_action() {
  # Wait for mysql to finish starting up first.
  while [[ ! -e /var/run/mysqld/mysqld.pid ]] ; do
      echo "waiting for mysql to come up"
      inotifywait -q -e create /var/run/mysqld/ >> /dev/null
  done

  post_start_action
}

pre_start_action

wait_for_mysql_and_run_post_start_action &

echo "Starting MySQL..."
exec /usr/sbin/mysqld --basedir=/usr --datadir=$DATA_DIR --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306


